---
engines:
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-2"
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
ratings:
  paths:
  - "**.scss"
  - "**.js"
exclude_paths:
- node_modules/
- script/
- doc/
- public/
- server/**/test.js
- server/test/
- client/**/*.hbs
- webpack.config.js
